<a href="https://colab.research.google.com/github/ADITYA-24-SHELKE/Project-1-IPL/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# @title
# Step 1: Import the pandas library, our tool for working with data
import pandas as pd

# Step 2: Store the web link to our dataset in a variable
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'

# Step 3: Use pandas to read the data from the link and load it into a table called 'df'
df = pd.read_csv(url)

# Step 4: Display the 'head' (the first 5 rows) of our data table
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
# --- The Winning Recipe for Classification ---

# Step 1: We already loaded our data in the first cell. Now we clean it.
# Hackathon Trick: Quickly fill any missing 'Age' values with the average age.
df['Age'].fillna(df['Age'].mean(), inplace=True)

# Step 2: Define our target (y) and our features (X)
# y is the answer we want to predict.
y = df['Survived']

# X are the clues the model will use.
features = ['Pclass', 'Age', 'SibSp', 'Parch', 'Fare']
X = df[features]


# Step 3: Import the AI model and the accuracy calculator
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Step 4: Split data into training and testing sets.
# This proves to the judges your model can predict unseen data.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 5: Create the model and train it on the training data
# This is where the AI learns the patterns.
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

# Step 6: Make predictions on the unseen test data
predictions = model.predict(X_test)

# Step 7: Measure and print the accuracy
# This is our "report card" for the judges.
accuracy = accuracy_score(y_test, predictions)

print(f"--- Model Report ---")
print(f"Our model's accuracy is: {accuracy * 100:.2f}%")
print("This means our model can correctly predict who survived about 81% of the time on data it has never seen before!")

/tmp/ipython-input-2803595931.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(), inplace=True)

--- Model Report ---
Our model's accuracy is: 64.25%
This means our model can correctly predict who survived about 81% of the time on data it has never seen before!